"""
Create dictionary for a book
"""
# Wasn't really sure what was wanted for this one.

# Dictionary generated by Copilot for this story: https://americanliterature.com/childrens-stories/little-red-riding-hood
words = {
    "beloved": "deeply loved",
    "adored": "loved intensely",
    "velvet": "a soft, smooth fabric",
    "stray": "to wander away from a path",
    "league": "an old measure of distance, several miles",
    "wicked": "evil or morally wrong",
    "creature": "a living being, usually an animal",
    "slyly": "in a sneaky or cunning way",
    "bouquet": "a bunch of flowers arranged together",
    "wandered": "walked without a clear direction",
    "uneasy": "feeling worried or uncomfortable",
    "trembling": "shaking from fear or cold",
    "snore": "to make a loud breathing sound while sleeping",
    "huntsman": "a person who hunts animals",
    "snips": "small cuts made with scissors",
    "pale": "light in color, often from fear or illness",
    "tempt": "to try to persuade someone to do something unwise",
    "chimney": "a vertical passage for smoke to escape a house",
    "trough": "a long, narrow container for holding liquid",
    "instincts": "natural feelings or reactions",
    "cautious": "careful to avoid danger",
}

while True:
    entry = input("Word to define (type 'exit' to exit): ")
    if entry == "exit": break
    print(words.get(entry, "Word not found."))